# Goal

* Simple Single Value Decomposition studies and exercises
* Rank of Matrix, SVD, eigen decomposition

In [8]:
import numpy as np

print ('First Matrix example')

#Matrix np array: A list of "lists" that are the row vectors of matrix
m = np.array(   [[1,3,1,4],
                [2,7,3,9],
                [1,5,3,1],
                [1,2,0,8]])

print(m)

print("Rank: " + str(np.linalg.matrix_rank(m))) 
print("Shape: " + str(m.shape))

First Matrix example
[[1 3 1 4]
 [2 7 3 9]
 [1 5 3 1]
 [1 2 0 8]]
Rank: 3
Shape: (4, 4)


## SVD

* Each column of $U$ and $V*$ form a set of **orthonormal vectors**
* Therefore, can be regarded as basis vectors

In [9]:
#Single value Decomposition of matrix m

U, S, VT = np.linalg.svd(m,full_matrices=0)

print("U:")
print("Rank: " + str(np.linalg.matrix_rank(U)))
print("Shape: " + str(U.shape))
print(U)
print("S:")
print("Rank: " + str(np.linalg.matrix_rank(S)))
print("Shape: " + str(S.shape))
print(S)
print("VT:")
print("Rank: " + str(np.linalg.matrix_rank(VT)))
print("Shape: " + str(VT.shape))
print(VT)

U:
Rank: 4
Shape: (4, 4)
[[-3.31035688e-01  1.16552991e-02  9.43546251e-01 -2.49009304e-18]
 [-7.61541216e-01  1.20573764e-01 -2.68670077e-01 -5.77350269e-01]
 [-2.79533664e-01  7.59592647e-01 -1.07455144e-01  5.77350269e-01]
 [-4.82007552e-01 -6.39018883e-01 -1.61214933e-01  5.77350269e-01]]
S:
Rank: 1
Shape: (4,)
[1.56792158e+01 5.39437562e+00 2.50807625e-01 2.13481008e-17]
VT:
Rank: 4
Shape: (4, 4)
[[-1.66823352e-01 -5.53954938e-01 -2.20308234e-01 -7.85345897e-01]
 [ 6.92159053e-02  6.30083620e-01  4.91651809e-01 -5.97061378e-01]
 [ 5.48372557e-01  3.59808132e-01 -7.36936981e-01 -1.63552844e-01]
 [-8.16496581e-01  4.08248290e-01 -4.08248290e-01 -2.55504445e-16]]


In [5]:
#Eigenvalue decomposition

eigenvalues, eigenvectors = np.linalg.eig(m)

print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[ 1.34988503e+01  5.36301779e+00  1.38131899e-01 -1.25312550e-15]
Eigenvectors:
[[-3.27792490e-01  1.35019574e-01 -9.83663903e-01  8.16496581e-01]
 [-7.69611159e-01  4.30632500e-01  1.45955949e-01 -4.08248290e-01]
 [-4.30082948e-01  8.08444899e-01  5.79676999e-02  4.08248290e-01]
 [-3.39528211e-01 -3.77812399e-01  8.79882487e-02  7.48248210e-16]]
